import type { IconComponent } from './runtime';
import { withIcon } from './runtime';
import AlertCircleIcon from '~icons/lucide/circle-alert';
import AlertTriangleIcon from '~icons/lucide/triangle-alert';
import AlignJustifyIcon from '~icons/lucide/text-align-justify';
import ArchiveIcon from '~icons/lucide/archive';
import ArchiveRestoreIcon from '~icons/lucide/archive-restore';
import ArrowBigUpIcon from '~icons/lucide/arrow-big-up';
import ArrowDownIcon from '~icons/lucide/arrow-down';
import ArrowLeftIcon from '~icons/lucide/arrow-left';
import ArrowRightIcon from '~icons/lucide/arrow-right';
import ArrowUpIcon from '~icons/lucide/arrow-up';
import ArrowUpDownIcon from '~icons/lucide/arrow-up-down';
import ArrowUpRightIcon from '~icons/lucide/arrow-up-right';
import BotIcon from '~icons/lucide/bot';
import BugIcon from '~icons/lucide/bug';
import CheckIcon from '~icons/lucide/check';
import CheckCircle2Icon from '~icons/lucide/circle-check';
import ChevronDownIcon from '~icons/lucide/chevron-down';
import ChevronLeftIcon from '~icons/lucide/chevron-left';
import ChevronRightIcon from '~icons/lucide/chevron-right';
import ChevronUpIcon from '~icons/lucide/chevron-up';
import CircleIcon from '~icons/lucide/circle';
import CircleDotIcon from '~icons/lucide/circle-dot';
import CircuitBoardIcon from '~icons/lucide/circuit-board';
import ClockIcon from '~icons/lucide/clock';
import Code2Icon from '~icons/lucide/file-code-2';
import Columns2Icon from '~icons/lucide/columns-2';
import CommandIcon from '~icons/lucide/command';
import CopyIcon from '~icons/lucide/copy';
import CornerDownLeftIcon from '~icons/lucide/corner-down-left';
import CpuIcon from '~icons/lucide/cpu';
import DownloadIcon from '~icons/lucide/download';
import Edit2Icon from '~icons/lucide/pencil';
import ExternalLinkIcon from '~icons/lucide/external-link';
import EyeIcon from '~icons/lucide/eye';
import EyeOffIcon from '~icons/lucide/eye-off';
import FileCodeIcon from '~icons/lucide/file-code';
import FileDiffIcon from '~icons/lucide/file-diff';
import FileTextIcon from '~icons/lucide/file-text';
import FolderIcon from '~icons/lucide/folder';
import FolderClosedIcon from '~icons/lucide/folder-closed';
import FolderGit2Icon from '~icons/lucide/folder-git-2';
import FolderOpenIcon from '~icons/lucide/folder-open';
import FolderPlusIcon from '~icons/lucide/folder-plus';
import GaugeIcon from '~icons/lucide/gauge';
import GitBranchIcon from '~icons/lucide/git-branch';
import GitBranchPlusIcon from '~icons/lucide/git-branch-plus';
import GitMergeIcon from '~icons/lucide/git-merge';
import GitPullRequestIcon from '~icons/lucide/git-pull-request';
import GithubIcon from '~icons/lucide/github';
import GlobeIcon from '~icons/lucide/globe';
import GripVerticalIcon from '~icons/lucide/grip-vertical';
import HeadphonesIcon from '~icons/lucide/headphones';
import HomeIcon from '~icons/lucide/house';
import InboxIcon from '~icons/lucide/inbox';
import InfoIcon from '~icons/lucide/info';
import KanbanSquareIcon from '~icons/lucide/square-kanban';
import KeyIcon from '~icons/lucide/key';
import KeyRoundIcon from '~icons/lucide/key-round';
import KeyboardIcon from '~icons/lucide/keyboard';
import LayersIcon from '~icons/lucide/layers';
import LayoutGridIcon from '~icons/lucide/layout-grid';
import ListFilterIcon from '~icons/lucide/list-filter';
import Loader2Icon from '~icons/lucide/loader-circle';
import LockIcon from '~icons/lucide/lock';
import LogInIcon from '~icons/lucide/log-in';
import LogOutIcon from '~icons/lucide/log-out';
import Maximize2Icon from '~icons/lucide/maximize-2';
import MessageCircleIcon from '~icons/lucide/message-circle';
import MessageSquareIcon from '~icons/lucide/message-square';
import Minimize2Icon from '~icons/lucide/minimize-2';
import MinusIcon from '~icons/lucide/minus';
import MinusCircleIcon from '~icons/lucide/circle-minus';
import MonitorIcon from '~icons/lucide/monitor';
import MoonIcon from '~icons/lucide/moon';
import MoreHorizontalIcon from '~icons/lucide/ellipsis';
import OptionIcon from '~icons/lucide/option';
import PaletteIcon from '~icons/lucide/palette';
import PanelLeftIcon from '~icons/lucide/panel-left';
import PanelRightIcon from '~icons/lucide/panel-right';
import PaperclipIcon from '~icons/lucide/paperclip';
import PauseIcon from '~icons/lucide/pause';
import PencilIcon from '~icons/lucide/pencil';
import PinIcon from '~icons/lucide/pin';
import PinOffIcon from '~icons/lucide/pin-off';
import PlayIcon from '~icons/lucide/play';
import PlugIcon from '~icons/lucide/plug';
import PlusIcon from '~icons/lucide/plus';
import PuzzleIcon from '~icons/lucide/puzzle';
import RefreshCcwIcon from '~icons/lucide/refresh-ccw';
import RefreshCwIcon from '~icons/lucide/refresh-cw';
import RotateCcwIcon from '~icons/lucide/rotate-ccw';
import RotateCwIcon from '~icons/lucide/rotate-cw';
import SaveIcon from '~icons/lucide/save';
import SearchIcon from '~icons/lucide/search';
import ServerIcon from '~icons/lucide/server';
import SettingsIcon from '~icons/lucide/settings';
import Settings2Icon from '~icons/lucide/settings-2';
import ShieldIcon from '~icons/lucide/shield';
import SparklesIcon from '~icons/lucide/sparkles';
import SquareIcon from '~icons/lucide/square';
import SunIcon from '~icons/lucide/sun';
import TagIcon from '~icons/lucide/tag';
import TerminalIcon from '~icons/lucide/terminal';
import TicketIcon from '~icons/lucide/ticket';
import TimerIcon from '~icons/lucide/timer';
import TrashIcon from '~icons/lucide/trash';
import Trash2Icon from '~icons/lucide/trash-2';
import Undo2Icon from '~icons/lucide/undo-2';
import UserIcon from '~icons/lucide/user';
import UsersIcon from '~icons/lucide/users';
import WorkflowIcon from '~icons/lucide/workflow';
import XIcon from '~icons/lucide/x';
import XCircleIcon from '~icons/lucide/circle-x';
import ZapIcon from '~icons/lucide/zap';

export type { IconComponent as LucideIcon } from './runtime';

export const AlertCircle: IconComponent = withIcon(AlertCircleIcon);
export const AlertTriangle: IconComponent = withIcon(AlertTriangleIcon);
export const AlignJustify: IconComponent = withIcon(AlignJustifyIcon);
export const Archive: IconComponent = withIcon(ArchiveIcon);
export const ArchiveRestore: IconComponent = withIcon(ArchiveRestoreIcon);
export const ArrowBigUp: IconComponent = withIcon(ArrowBigUpIcon);
export const ArrowDown: IconComponent = withIcon(ArrowDownIcon);
export const ArrowLeft: IconComponent = withIcon(ArrowLeftIcon);
export const ArrowRight: IconComponent = withIcon(ArrowRightIcon);
export const ArrowUp: IconComponent = withIcon(ArrowUpIcon);
export const ArrowUpDown: IconComponent = withIcon(ArrowUpDownIcon);
export const ArrowUpRight: IconComponent = withIcon(ArrowUpRightIcon);
export const Bot: IconComponent = withIcon(BotIcon);
export const Bug: IconComponent = withIcon(BugIcon);
export const Check: IconComponent = withIcon(CheckIcon);
export const CheckCircle2: IconComponent = withIcon(CheckCircle2Icon);
export const ChevronDown: IconComponent = withIcon(ChevronDownIcon);
export const ChevronLeft: IconComponent = withIcon(ChevronLeftIcon);
export const ChevronRight: IconComponent = withIcon(ChevronRightIcon);
export const ChevronUp: IconComponent = withIcon(ChevronUpIcon);
export const Circle: IconComponent = withIcon(CircleIcon);
export const CircleDot: IconComponent = withIcon(CircleDotIcon);
export const CircuitBoard: IconComponent = withIcon(CircuitBoardIcon);
export const Clock: IconComponent = withIcon(ClockIcon);
export const Code2: IconComponent = withIcon(Code2Icon);
export const Columns2: IconComponent = withIcon(Columns2Icon);
export const Command: IconComponent = withIcon(CommandIcon);
export const Copy: IconComponent = withIcon(CopyIcon);
export const CornerDownLeft: IconComponent = withIcon(CornerDownLeftIcon);
export const Cpu: IconComponent = withIcon(CpuIcon);
export const Download: IconComponent = withIcon(DownloadIcon);
export const Edit2: IconComponent = withIcon(Edit2Icon);
export const ExternalLink: IconComponent = withIcon(ExternalLinkIcon);
export const Eye: IconComponent = withIcon(EyeIcon);
export const EyeOff: IconComponent = withIcon(EyeOffIcon);
export const FileCode: IconComponent = withIcon(FileCodeIcon);
export const FileDiff: IconComponent = withIcon(FileDiffIcon);
export const FileText: IconComponent = withIcon(FileTextIcon);
export const Folder: IconComponent = withIcon(FolderIcon);
export const FolderClosed: IconComponent = withIcon(FolderClosedIcon);
export const FolderGit2: IconComponent = withIcon(FolderGit2Icon);
export const FolderOpen: IconComponent = withIcon(FolderOpenIcon);
export const FolderPlus: IconComponent = withIcon(FolderPlusIcon);
export const Gauge: IconComponent = withIcon(GaugeIcon);
export const GitBranch: IconComponent = withIcon(GitBranchIcon);
export const GitBranchPlus: IconComponent = withIcon(GitBranchPlusIcon);
export const GitMerge: IconComponent = withIcon(GitMergeIcon);
export const GitPullRequest: IconComponent = withIcon(GitPullRequestIcon);
export const Github: IconComponent = withIcon(GithubIcon);
export const Globe: IconComponent = withIcon(GlobeIcon);
export const GripVertical: IconComponent = withIcon(GripVerticalIcon);
export const Headphones: IconComponent = withIcon(HeadphonesIcon);
export const Home: IconComponent = withIcon(HomeIcon);
export const Inbox: IconComponent = withIcon(InboxIcon);
export const Info: IconComponent = withIcon(InfoIcon);
export const KanbanSquare: IconComponent = withIcon(KanbanSquareIcon);
export const Key: IconComponent = withIcon(KeyIcon);
export const KeyRound: IconComponent = withIcon(KeyRoundIcon);
export const Keyboard: IconComponent = withIcon(KeyboardIcon);
export const Layers: IconComponent = withIcon(LayersIcon);
export const LayoutGrid: IconComponent = withIcon(LayoutGridIcon);
export const ListFilter: IconComponent = withIcon(ListFilterIcon);
export const Loader2: IconComponent = withIcon(Loader2Icon);
export const Lock: IconComponent = withIcon(LockIcon);
export const LogIn: IconComponent = withIcon(LogInIcon);
export const LogOut: IconComponent = withIcon(LogOutIcon);
export const Maximize2: IconComponent = withIcon(Maximize2Icon);
export const MessageCircle: IconComponent = withIcon(MessageCircleIcon);
export const MessageSquare: IconComponent = withIcon(MessageSquareIcon);
export const Minimize2: IconComponent = withIcon(Minimize2Icon);
export const Minus: IconComponent = withIcon(MinusIcon);
export const MinusCircle: IconComponent = withIcon(MinusCircleIcon);
export const Monitor: IconComponent = withIcon(MonitorIcon);
export const Moon: IconComponent = withIcon(MoonIcon);
export const MoreHorizontal: IconComponent = withIcon(MoreHorizontalIcon);
export const Option: IconComponent = withIcon(OptionIcon);
export const Palette: IconComponent = withIcon(PaletteIcon);
export const PanelLeft: IconComponent = withIcon(PanelLeftIcon);
export const PanelRight: IconComponent = withIcon(PanelRightIcon);
export const Paperclip: IconComponent = withIcon(PaperclipIcon);
export const Pause: IconComponent = withIcon(PauseIcon);
export const Pencil: IconComponent = withIcon(PencilIcon);
export const Pin: IconComponent = withIcon(PinIcon);
export const PinOff: IconComponent = withIcon(PinOffIcon);
export const Play: IconComponent = withIcon(PlayIcon);
export const Plug: IconComponent = withIcon(PlugIcon);
export const Plus: IconComponent = withIcon(PlusIcon);
export const Puzzle: IconComponent = withIcon(PuzzleIcon);
export const RefreshCcw: IconComponent = withIcon(RefreshCcwIcon);
export const RefreshCw: IconComponent = withIcon(RefreshCwIcon);
export const RotateCcw: IconComponent = withIcon(RotateCcwIcon);
export const RotateCw: IconComponent = withIcon(RotateCwIcon);
export const Save: IconComponent = withIcon(SaveIcon);
export const Search: IconComponent = withIcon(SearchIcon);
export const Server: IconComponent = withIcon(ServerIcon);
export const Settings: IconComponent = withIcon(SettingsIcon);
export const Settings2: IconComponent = withIcon(Settings2Icon);
export const Shield: IconComponent = withIcon(ShieldIcon);
export const Sparkles: IconComponent = withIcon(SparklesIcon);
export const Square: IconComponent = withIcon(SquareIcon);
export const Sun: IconComponent = withIcon(SunIcon);
export const Tag: IconComponent = withIcon(TagIcon);
export const Terminal: IconComponent = withIcon(TerminalIcon);
export const Ticket: IconComponent = withIcon(TicketIcon);
export const Timer: IconComponent = withIcon(TimerIcon);
export const Trash: IconComponent = withIcon(TrashIcon);
export const Trash2: IconComponent = withIcon(Trash2Icon);
export const Undo2: IconComponent = withIcon(Undo2Icon);
export const User: IconComponent = withIcon(UserIcon);
export const Users: IconComponent = withIcon(UsersIcon);
export const Workflow: IconComponent = withIcon(WorkflowIcon);
export const X: IconComponent = withIcon(XIcon);
export const XCircle: IconComponent = withIcon(XCircleIcon);
export const Zap: IconComponent = withIcon(ZapIcon);
