import { withIcon } from '../runtime';
import SiTypescriptIcon from '~icons/simple-icons/typescript';
import SiJavascriptIcon from '~icons/simple-icons/javascript';
import SiReactIcon from '~icons/simple-icons/react';
import SiPythonIcon from '~icons/simple-icons/python';
import SiHtml5Icon from '~icons/simple-icons/html5';
import SiCss3Icon from '~icons/simple-icons/css3';
import SiSassIcon from '~icons/simple-icons/sass';
import SiNodedotjsIcon from '~icons/simple-icons/nodedotjs';
import SiNpmIcon from '~icons/simple-icons/npm';
import SiYarnIcon from '~icons/simple-icons/yarn';
import SiDockerIcon from '~icons/simple-icons/docker';
import SiGitIcon from '~icons/simple-icons/git';
import SiGoIcon from '~icons/simple-icons/go';
import SiRustIcon from '~icons/simple-icons/rust';
import SiCplusplusIcon from '~icons/simple-icons/cplusplus';
import SiPhpIcon from '~icons/simple-icons/php';
import SiRubyIcon from '~icons/simple-icons/ruby';
import SiSwiftIcon from '~icons/simple-icons/swift';
import SiKotlinIcon from '~icons/simple-icons/kotlin';
import SiLuaIcon from '~icons/simple-icons/lua';
import SiVuedotjsIcon from '~icons/simple-icons/vuedotjs';
import SiAngularIcon from '~icons/simple-icons/angular';
import SiSvelteIcon from '~icons/simple-icons/svelte';
import SiNextdotjsIcon from '~icons/simple-icons/nextdotjs';
import SiGraphqlIcon from '~icons/simple-icons/graphql';
import SiPostgresqlIcon from '~icons/simple-icons/postgresql';
import SiMongodbIcon from '~icons/simple-icons/mongodb';
import SiRedisIcon from '~icons/simple-icons/redis';
import SiWebpackIcon from '~icons/simple-icons/webpack';
import SiViteIcon from '~icons/simple-icons/vite';
import SiEslintIcon from '~icons/simple-icons/eslint';
import SiPrettierIcon from '~icons/simple-icons/prettier';
import SiJestIcon from '~icons/simple-icons/jest';
import SiCypressIcon from '~icons/simple-icons/cypress';
import SiStorybookIcon from '~icons/simple-icons/storybook';
import SiTailwindcssIcon from '~icons/simple-icons/tailwindcss';
import SiBabelIcon from '~icons/simple-icons/babel';

export const SiTypescript = withIcon(SiTypescriptIcon);
export const SiJavascript = withIcon(SiJavascriptIcon);
export const SiReact = withIcon(SiReactIcon);
export const SiPython = withIcon(SiPythonIcon);
export const SiHtml5 = withIcon(SiHtml5Icon);
export const SiCss3 = withIcon(SiCss3Icon);
export const SiSass = withIcon(SiSassIcon);
export const SiNodedotjs = withIcon(SiNodedotjsIcon);
export const SiNpm = withIcon(SiNpmIcon);
export const SiYarn = withIcon(SiYarnIcon);
export const SiDocker = withIcon(SiDockerIcon);
export const SiGit = withIcon(SiGitIcon);
export const SiGo = withIcon(SiGoIcon);
export const SiRust = withIcon(SiRustIcon);
export const SiCplusplus = withIcon(SiCplusplusIcon);
export const SiPhp = withIcon(SiPhpIcon);
export const SiRuby = withIcon(SiRubyIcon);
export const SiSwift = withIcon(SiSwiftIcon);
export const SiKotlin = withIcon(SiKotlinIcon);
export const SiLua = withIcon(SiLuaIcon);
export const SiVuedotjs = withIcon(SiVuedotjsIcon);
export const SiAngular = withIcon(SiAngularIcon);
export const SiSvelte = withIcon(SiSvelteIcon);
export const SiNextdotjs = withIcon(SiNextdotjsIcon);
export const SiGraphql = withIcon(SiGraphqlIcon);
export const SiPostgresql = withIcon(SiPostgresqlIcon);
export const SiMongodb = withIcon(SiMongodbIcon);
export const SiRedis = withIcon(SiRedisIcon);
export const SiWebpack = withIcon(SiWebpackIcon);
export const SiVite = withIcon(SiViteIcon);
export const SiEslint = withIcon(SiEslintIcon);
export const SiPrettier = withIcon(SiPrettierIcon);
export const SiJest = withIcon(SiJestIcon);
export const SiCypress = withIcon(SiCypressIcon);
export const SiStorybook = withIcon(SiStorybookIcon);
export const SiTailwindcss = withIcon(SiTailwindcssIcon);
export const SiBabel = withIcon(SiBabelIcon);
