import { withIcon } from '../runtime';
import VscFileIcon from '~icons/lucide/file';
import VscFolderIcon from '~icons/lucide/folder';
import VscFolderOpenedIcon from '~icons/lucide/folder-open';
import VscJsonIcon from '~icons/lucide/braces';
import VscMarkdownIcon from '~icons/lucide/file-text';
import VscFileCodeIcon from '~icons/lucide/file-code-2';
import VscFileBinaryIcon from '~icons/lucide/file-code-2';
import VscFileMediaIcon from '~icons/lucide/file-video-camera';
import VscFilePdfIcon from '~icons/lucide/file-text';
import VscFileZipIcon from '~icons/lucide/file-archive';
import VscTerminalIcon from '~icons/lucide/terminal';
import VscSettingsGearIcon from '~icons/lucide/settings';
import VscDatabaseIcon from '~icons/lucide/database';
import VscLockIcon from '~icons/lucide/lock';
import VscKeyIcon from '~icons/lucide/key-round';
import VscTableIcon from '~icons/lucide/table-properties';
import VscSymbolMiscIcon from '~icons/lucide/flask-conical';
import VscErrorIcon from '~icons/lucide/triangle-alert';

export const VscFile = withIcon(VscFileIcon);
export const VscFolder = withIcon(VscFolderIcon);
export const VscFolderOpened = withIcon(VscFolderOpenedIcon);
export const VscJson = withIcon(VscJsonIcon);
export const VscMarkdown = withIcon(VscMarkdownIcon);
export const VscFileCode = withIcon(VscFileCodeIcon);
export const VscFileBinary = withIcon(VscFileBinaryIcon);
export const VscFileMedia = withIcon(VscFileMediaIcon);
export const VscFilePdf = withIcon(VscFilePdfIcon);
export const VscFileZip = withIcon(VscFileZipIcon);
export const VscTerminal = withIcon(VscTerminalIcon);
export const VscSettingsGear = withIcon(VscSettingsGearIcon);
export const VscDatabase = withIcon(VscDatabaseIcon);
export const VscLock = withIcon(VscLockIcon);
export const VscKey = withIcon(VscKeyIcon);
export const VscTable = withIcon(VscTableIcon);
export const VscSymbolMisc = withIcon(VscSymbolMiscIcon);
export const VscError = withIcon(VscErrorIcon);
